name: Run CLS Request

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install required Python libraries
      run: |
        python -m pip install requests

    - name: Run Request
      env:
        CODE : ${{ secrets.CODE }}
        COOKIE: ${{ secrets.COOKIE }}
        HEADER_JSON: ${{ secrets.HEADER_JSON }}
        NAME: ${{ secrets.NAME }}
        NOHP: ${{ secrets.NOHP }}
        PARAM: ${{ secrets.PARAM }}
        TMP: ${{ secrets.TMP }}
        URL: ${{ secrets.URL }}
      run: |
        python cls.py
