name: Run CLS Request

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install required Python libraries
      run: |
        python -m pip install requests

    - name: Check if hour.txt has only one line
      id: check-hour-txt
      run: |
        if [ -f "hour.txt" ]; then
          line_count=$(wc -l < hour.txt)
          if [ "$line_count" -eq 1 ]; then
            echo "hour.txt contains only one line."
            echo "run_script=true" >> $GITHUB_ENV
          else
            echo "hour.txt does not contain only one line."
            echo "run_script=false" >> $GITHUB_ENV
          fi
        else
          echo "hour.txt not found."
          echo "run_script=false" >> $GITHUB_ENV
        fi

    - name: Run Request
      if: env.run_script == 'true'
      env:
        CODE : ${{ secrets.CODE }}
        COOKIE: ${{ secrets.COOKIE }}
        HEADER_JSON: ${{ secrets.HEADER_JSON }}
        NAME: ${{ secrets.NAME }}
        NOHP: ${{ secrets.NOHP }}
        PARAM: ${{ secrets.PARAM }}
        TMP: ${{ secrets.TMP }}
        URL: ${{ secrets.URL }}
      run: |
        python cls.py

    - name: Modify hour.txt to keep only the first line
      if: env.run_script == 'true'
      run: |
        if [ -f "hour.txt" ]; then
          sed -i '1!d' hour.txt
          echo "hour.txt modified to keep only the first line:"
          cat hour.txt
        else
          echo "hour.txt not found, skipping modification."
        fi
